---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: virt-controller
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  - pods
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
  - update
- apiGroups:
  - ""
  resources:
  - persistentvolumeclaims
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - cdi.kubevirt.io
  resources:
  - datavolumes
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - k8s.cni.cncf.io
  resources:
  - network-attachment-definitions
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - virt.virtink.smartx.com
  resources:
  - virtualmachinemigrations
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - virt.virtink.smartx.com
  resources:
  - virtualmachinemigrations/status
  - virtualmachinereplicasets/scale
  - virtualmachinereplicasets/status
  - virtualmachines/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - virt.virtink.smartx.com
  resources:
  - virtualmachinereplicasets
  - virtualmachines
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - virt.virtink.smartx.com
  resources:
  - virtualmachines/finalizers
  verbs:
  - update
