apiVersion: virt.virtink.smartx.com/v1alpha1
kind: VirtualMachineReplicaSet
metadata:
  name: ubuntu-vmr
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: test-vm
  template:
    metadata:
      labels:
        app: test-vm
    spec:
      readinessProbe:
        httpGet:
          scheme: HTTP
          port: 80
      instance:
        memory:
          size: 1Gi
        disks:
          - name: ubuntu
          - name: cloud-init
        interfaces:
          - name: pod
      volumes:
        - name: ubuntu
          containerDisk:
            image: smartxworks/virtink-container-disk-ubuntu
            imagePullPolicy: IfNotPresent
        - name: cloud-init
          cloudInit:
            userData: |-
              #cloud-config
              password: password
              chpasswd: { expire: False }
              ssh_pwauth: True
              packages:
                - nginx
              runcmd:
                - [ "systemctl", "enable", "--now", "nginx" ]
      networks:
        - name: pod
          pod: {} 