apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubrid-controller
  namespace: kubrid-system
spec:
  selector:
    matchLabels:
      name: kubrid-controller
  template:
    metadata:
      labels:
        name: kubrid-controller
    spec:
      serviceAccountName: kubrid-controller
      containers:
        - name: kubrid-controller
          image: kubrid-controller
          args:
            - --zap-time-encoding=iso8601
            - --leader-elect
          volumeMounts:
            - name: cert
              mountPath: /tmp/k8s-webhook-server/serving-certs
              readOnly: true
      volumes:
        - name: cert
          secret:
            secretName: kubrid-controller-cert
            defaultMode: 0644
