apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: kubrid-daemon
  namespace: kubrid-system
spec:
  selector:
    matchLabels:
      name: kubrid-daemon
  template:
    metadata:
      labels:
        name: kubrid-daemon
    spec:
      serviceAccountName: kubrid-daemon
      containers:
        - name: kubrid-daemon
          image: kubrid-daemon
          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          args:
            - --zap-time-encoding=iso8601
          volumeMounts:
            - name: kubelet-pods
              mountPath: /var/lib/kubelet/pods
      volumes:
        - name: kubelet-pods
          hostPath:
            path: /var/lib/kubelet/pods
