---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: kubrid-daemon
rules:
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
  - update
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - kubrid.smartx.com
  resources:
  - virtualmachines
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - kubrid.smartx.com
  resources:
  - virtualmachines/finalizers
  verbs:
  - update
- apiGroups:
  - kubrid.smartx.com
  resources:
  - virtualmachines/status
  verbs:
  - get
  - patch
  - update
